### PR TITLE
attempt to fixing open issue - icons bug

### PR DESCRIPTION
**Pull request by WikiNetworks**
Corey, believe I have a potential solution for #1

### CODE REVIEW

**Comment by penguinstyles** [comment]
So, if you take a quick look at the FontAwesome website you’ll notice there’s (currently) no fa-purge icon. :)

**Comment by WikiNetworks** [comment]
I added in moving pages along with the missing icons (need resizing) that FontAwesome doesn't have.

**Comment by WikiNetworks** [comment]
purge icon: https://fontawesome.com/icons/sync?style=solid
unicode: f021
move icon: https://fontawesome.com/icons/arrow-alt-circle-right?style=solid
unicode: f35a

**Comment by penguinstyles** [comment]
Heya, did you test the changes you made in a live MediaWiki installation? If you do you'll receive the following error:

`[Sun Mar 18 06:06:12.851165 2018] [:error] [pid 26345] [client x.x.x.x:55497] PHP Warning:  htmlspecialchars() expects parameter 1 to be string, object given in Editorial/templates/header.php on line 4, referer: http://localhost/Special:RecentChanges`

:)

**Comment by WikiNetworks** [comment]
ok finally was able to get it actually working realistically rather than theoretically... that was tricky. got it using manual:skinning part 2

**Comment by penguinstyles** [comment]
That works! Good job :)

**Pull request merged**
